list = []
list1=input("enter a item: ")
list.append(list1)
list2=input("enter a item: ")
list.append(list2)
list3=input("enter a item: ")
list.append(list3)
list4=input("enter a item: ")
list.append(list4)
list5=input("enter a item: ")
list.append(list5)
list6=input("enter a item: ")
list.append(list6)
list7=input("enter a item: ")
list.append(list7)
print(list)