list = []
list1=int(input("enter a marks: "))
list.append(list1)
list2=int(input("enter a marks: "))
list.append(list2)
list3=int(input("enter a marks: "))
list.append(list3)
list4=int(input("enter a marks: "))
list.append(list4)
list5=int(input("enter a marks: "))
list.append(list5)
list6=int(input("enter a marks: "))
list.append(list6)
list.sort()
print(list)
